export const summaryRows = [
  ['2024-03-25', '', 1, 11],
  ['2024-03-26', '', 2, 22],
  ['', '', 100, 200],
]

export const datasetJson = {
  id: 625,
  name: '测试数据集_预发_0913',
  description: '',
  version: 7,
  lastEditVersion: 7,
  versionId: 625,
  realId: 9478,
  creator: 'bi-li.huifang',
  operator: 'bi-li.huifang',
  docUrl: '',
  workspaceId: 7,
  status: 'ONLINE',
  createTime: '2022-09-13 11:28:35',
  updateTime: '2023-09-13 10:29:50',
  creatorChinesName: '李慧芳(南枫)',
  operatorChinesName: '李慧芳(南枫)',
  groupId: 133,
  fields: [
    {
      id: 619000,
      name: 'dt',
      fieldExpression: 'dt',
      sourceFieldName: 'dt',
      operation: 'SUM',
      displayName: '日期，格式为yyyy-mm-dd',
      category: 'PROPERTY',
      dataType: 'TIME_YYYYMMDD',
      originDataType: 'TIME_YYYYMMDD',
      databaseDataType: 'Date',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '日期，格式为yyyy-mm-dd',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 1,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619001,
      name: 'gift_name',
      fieldExpression: 'gift_name',
      sourceFieldName: 'gift_name',
      operation: 'SUM',
      displayName: '礼物名称test12345',
      category: 'PROPERTY',
      dataType: 'TEXT',
      originDataType: 'TEXT',
      databaseDataType: 'String',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物名称',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 2,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619002,
      name: 'gift_type',
      fieldExpression: 'gift_type',
      sourceFieldName: 'gift_type',
      operation: 'SUM',
      displayName: '礼物类型:enum{普通消费礼物(nor',
      category: 'PROPERTY',
      dataType: 'TEXT',
      originDataType: 'TEXT',
      databaseDataType: 'String',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '礼物类型:enum{普通消费礼物(normal),金币消费礼物(coin),金豆消费礼物(bean)}',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 3,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619003,
      name: 'display_situation',
      fieldExpression: 'display_situation',
      sourceFieldName: 'display_situation',
      operation: 'SUM',
      displayName: '展示场景类型:set{房间(room),',
      category: 'PROPERTY',
      dataType: 'TEXT',
      originDataType: 'TEXT',
      databaseDataType: 'String',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '展示场景类型:set{房间(room),私聊(chat),订单(order),坐骑(mounts),装扮(decorate)}',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 4,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619004,
      name: 'first_consume_time',
      fieldExpression: 'toDateOrNull(first_consume_time)',
      sourceFieldName: 'first_consume_time',
      operation: 'SUM',
      displayName: '礼物首次使用时间 yy-mm-dd hh',
      category: 'PROPERTY',
      dataType: 'TIME',
      originDataType: 'TEXT',
      databaseDataType: 'String',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物首次使用时间 yy-mm-dd hh:mm:ss [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 5,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619005,
      name: 'last_consume_time',
      fieldExpression: 'toDateOrNull(last_consume_time)',
      sourceFieldName: 'last_consume_time',
      operation: 'SUM',
      displayName: '礼物最近使用时间 yy-mm-dd hh',
      category: 'PROPERTY',
      dataType: 'TIME',
      originDataType: 'TEXT',
      databaseDataType: 'String',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物最近使用时间 yy-mm-dd hh:mm:ss [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 6,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619006,
      name: 'app_id',
      fieldExpression: 'app_id',
      sourceFieldName: 'app_id',
      operation: 'SUM',
      displayName: '应用id:1->伴伴,2->皮队友,3-',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '应用id:1->伴伴,2->皮队友,3->谁是凶手,4->开心玩,6->新冲鸭',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 7,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619007,
      name: 'gift_id',
      fieldExpression: 'gift_id',
      sourceFieldName: 'gift_id',
      operation: 'SUM',
      displayName: '礼物id',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物id',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 8,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619008,
      name: 'gift_price',
      fieldExpression: 'gift_price',
      sourceFieldName: 'gift_price',
      operation: 'SUM',
      displayName: '礼物价格，单价：元',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Decimal(24, 4)',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物价格，单价：元',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 9,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619009,
      name: 'gift_price_point',
      fieldExpression: 'gift_price_point',
      sourceFieldName: 'gift_price_point',
      operation: 'SUM',
      displayName: '礼物价格，单价：分',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物价格，单价：分',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 10,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619010,
      name: 'is_deleted',
      fieldExpression: 'is_deleted',
      sourceFieldName: 'is_deleted',
      operation: 'SUM',
      displayName: '是否有效:0-上架,1-下架',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int32',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '是否有效:0-上架,1-下架',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 11,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619011,
      name: 'noble_title_level',
      fieldExpression: 'noble_title_level',
      sourceFieldName: 'noble_title_level',
      operation: 'SUM',
      displayName: '爵位等级',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int32',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '爵位等级',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 12,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619012,
      name: 'first_consume_timestamp',
      fieldExpression: 'first_consume_timestamp',
      sourceFieldName: 'first_consume_timestamp',
      operation: 'SUM',
      displayName: '礼物首次使用时间戳 [在对应应用app内',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物首次使用时间戳 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 13,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619013,
      name: 'last_consume_timestamp',
      fieldExpression: 'last_consume_timestamp',
      sourceFieldName: 'last_consume_timestamp',
      operation: 'SUM',
      displayName: '礼物最近使用时间戳 [在对应应用app内',
      category: 'PROPERTY',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '礼物最近使用时间戳 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 14,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619014,
      name: 'test123_2',
      fieldExpression: '[display_situation]',
      fieldExpressionTransform: '[display_situation]',
      sourceFieldName: 'null.dt,null.display_situation',
      operation: 'SUM',
      displayName: 'test123',
      type: 'ADD',
      category: 'PROPERTY',
      dataType: 'TEXT',
      originDataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: 'test123',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 15,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619015,
      name: 'test123_1',
      fieldExpression: '[display_situation]',
      fieldExpressionTransform: '[display_situation]',
      sourceFieldName: 'null.dt,null.display_situation',
      operation: 'SUM',
      displayName: 'test123',
      type: 'ADD',
      category: 'PROPERTY',
      dataType: 'TEXT',
      originDataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: 'test123',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 16,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619016,
      name: 'test123',
      fieldExpression: '[display_situation]',
      fieldExpressionTransform: '[display_situation]',
      sourceFieldName: 'null.dt,null.display_situation',
      operation: 'SUM',
      displayName: 'test123',
      type: 'ADD',
      category: 'PROPERTY',
      dataType: 'TEXT',
      originDataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: 'test123',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 17,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619017,
      name: 'test4',
      fieldExpression: '[gift_name]',
      fieldExpressionTransform: '[gift_name]',
      sourceFieldName: 'null.gift_name,null.dt',
      operation: 'SUM',
      displayName: 'test4',
      type: 'ADD',
      category: 'PROPERTY',
      dataType: 'TEXT',
      originDataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: 'test4',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 18,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619018,
      name: 'consume_dst_user_cnt_da_001',
      fieldExpression: 'consume_dst_user_cnt_da_001',
      sourceFieldName: 'consume_dst_user_cnt_da_001',
      operation: 'SUM',
      displayName: '历史累计总被打赏人数 [在对应应用app',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计总被打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 20,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619019,
      name: 'consume_cnt_da_001',
      fieldExpression: 'consume_cnt_da_001',
      sourceFieldName: 'consume_cnt_da_001',
      operation: 'SUM',
      displayName: '历史累计总打赏次数 [在对应应用app内',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计总打赏次数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 21,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619020,
      name: 'consume_amt_da_001',
      fieldExpression: 'consume_amt_da_001',
      sourceFieldName: 'consume_amt_da_001',
      operation: 'SUM',
      displayName: '历史累计总打赏金额{单位与礼物类型有关:',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '历史累计总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 22,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619021,
      name: 'consume_user_cnt_da_002',
      fieldExpression: 'consume_user_cnt_da_002',
      sourceFieldName: 'consume_user_cnt_da_002',
      operation: 'SUM',
      displayName: '历史累计房间内总打赏人数 [在对应应用a',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计房间内总打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 23,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619022,
      name: 'consume_dst_user_cnt_da_002',
      fieldExpression: 'consume_dst_user_cnt_da_002',
      sourceFieldName: 'consume_dst_user_cnt_da_002',
      operation: 'SUM',
      displayName: '历史累计房间内总被打赏人数 [在对应应用',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计房间内总被打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 24,
      createTime: '2023-09-13 10:29:50',
      updateTime: '2023-09-13 10:29:50',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619023,
      name: 'consume_cnt_da_002',
      fieldExpression: 'consume_cnt_da_002',
      sourceFieldName: 'consume_cnt_da_002',
      operation: 'SUM',
      displayName: '历史累计房间内总打赏次数 [在对应应用a',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计房间内总打赏次数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 25,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619024,
      name: 'consume_amt_da_002',
      fieldExpression: 'consume_amt_da_002',
      sourceFieldName: 'consume_amt_da_002',
      operation: 'SUM',
      displayName: '历史累计房间内总打赏金额{单位与礼物类型',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '历史累计房间内总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 26,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619025,
      name: 'consume_user_cnt_da_001',
      fieldExpression: 'consume_user_cnt_da_001',
      sourceFieldName: 'consume_user_cnt_da_001',
      operation: 'SUM',
      displayName: '历史累计总打赏人数 [在对应应用app内',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计总打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 27,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619026,
      name: 'consume_user_cnt_da_003',
      fieldExpression: 'consume_user_cnt_da_003',
      sourceFieldName: 'consume_user_cnt_da_003',
      operation: 'SUM',
      displayName: '历史累计房间外总打赏人数 [在对应应用a',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计房间外总打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 28,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619027,
      name: 'consume_dst_user_cnt_da_003',
      fieldExpression: 'consume_dst_user_cnt_da_003',
      sourceFieldName: 'consume_dst_user_cnt_da_003',
      operation: 'SUM',
      displayName: '历史累计房间外总被打赏人数 [在对应应用',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计房间外总被打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 29,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619028,
      name: 'consume_cnt_da_003',
      fieldExpression: 'consume_cnt_da_003',
      sourceFieldName: 'consume_cnt_da_003',
      operation: 'SUM',
      displayName: '历史累计房间外总打赏次数 [在对应应用a',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '历史累计房间外总打赏次数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 30,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619029,
      name: 'consume_amt_da_003',
      fieldExpression: 'consume_amt_da_003',
      sourceFieldName: 'consume_amt_da_003',
      operation: 'SUM',
      displayName: '历史累计房间外总打赏金额{单位与礼物类型',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '历史累计房间外总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 31,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619030,
      name: 'consume_user_cnt_1d_001',
      fieldExpression: 'consume_user_cnt_1d_001',
      sourceFieldName: 'consume_user_cnt_1d_001',
      operation: 'SUM',
      displayName: '最近1天总打赏人数 [在对应应用app内',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天总打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 32,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619031,
      name: 'consume_dst_user_cnt_1d_001',
      fieldExpression: 'consume_dst_user_cnt_1d_001',
      sourceFieldName: 'consume_dst_user_cnt_1d_001',
      operation: 'SUM',
      displayName: '最近1天总被打赏人数 [在对应应用app',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天总被打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 33,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619032,
      name: 'consume_cnt_1d_001',
      fieldExpression: 'consume_cnt_1d_001',
      sourceFieldName: 'consume_cnt_1d_001',
      operation: 'SUM',
      displayName: '最近1天总打赏次数 [在对应应用app内',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天总打赏次数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 34,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      computeExpression: '/10',
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619033,
      name: 'consume_amt_1d_001',
      fieldExpression: 'consume_amt_1d_001',
      sourceFieldName: 'consume_amt_1d_001',
      operation: 'SUM',
      displayName: '最近1天总打赏金额{单位与礼物类型有关:',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '最近1天总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 35,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619034,
      name: 'consume_user_cnt_1d_006',
      fieldExpression: 'consume_user_cnt_1d_006',
      sourceFieldName: 'consume_user_cnt_1d_006',
      operation: 'SUM',
      displayName: '最近1天房间内打赏人数 [在对应应用ap',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天房间内打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 36,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619035,
      name: 'consume_dst_user_cnt_1d_002',
      fieldExpression: 'consume_dst_user_cnt_1d_002',
      sourceFieldName: 'consume_dst_user_cnt_1d_002',
      operation: 'SUM',
      displayName: '最近1天房间内被打赏人数 [在对应应用a',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天房间内被打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 37,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619036,
      name: 'consume_cnt_1d_028',
      fieldExpression: 'consume_cnt_1d_028',
      sourceFieldName: 'consume_cnt_1d_028',
      operation: 'SUM',
      displayName: '最近1天房间内打赏次数 [在对应应用ap',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天房间内打赏次数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 38,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619037,
      name: 'consume_amt_1d_028',
      fieldExpression: 'consume_amt_1d_028',
      sourceFieldName: 'consume_amt_1d_028',
      operation: 'SUM',
      displayName: '最近1天房间内打赏金额{单位与礼物类型有',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '最近1天房间内打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 39,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619038,
      name: 'consume_user_cnt_1d_007',
      fieldExpression: 'consume_user_cnt_1d_007',
      sourceFieldName: 'consume_user_cnt_1d_007',
      operation: 'SUM',
      displayName: '最近1天房间外打赏人数 [在对应应用ap',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天房间外打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 40,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619039,
      name: 'consume_dst_user_cnt_1d_003',
      fieldExpression: 'consume_dst_user_cnt_1d_003',
      sourceFieldName: 'consume_dst_user_cnt_1d_003',
      operation: 'SUM',
      displayName: '最近1天房间外被打赏人数 [在对应应用a',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天房间外被打赏人数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 41,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619040,
      name: 'consume_cnt_1d_029',
      fieldExpression: 'consume_cnt_1d_029',
      sourceFieldName: 'consume_cnt_1d_029',
      operation: 'SUM',
      displayName: '最近1天房间外打赏次数 [在对应应用ap',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近1天房间外打赏次数 [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 42,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619041,
      name: 'consume_amt_1d_029',
      fieldExpression: 'consume_amt_1d_029',
      sourceFieldName: 'consume_amt_1d_029',
      operation: 'SUM',
      displayName: '最近1天房间外打赏金额{单位与礼物类型有',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '最近1天房间外打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 43,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619042,
      name: 'consume_amt_1d_034',
      fieldExpression: 'consume_amt_1d_034',
      sourceFieldName: 'consume_amt_1d_034',
      operation: 'SUM',
      displayName:
        '消耗背包物品总金额，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-01日',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '消耗背包物品总金额，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-01日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 44,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619043,
      name: 'discount_amt_1d_002',
      fieldExpression: 'discount_amt_1d_002',
      sourceFieldName: 'discount_amt_1d_002',
      operation: 'SUM',
      displayName:
        '使用优惠券的减免金额，包含背包中使用优惠券场景，2022-11-30分区生效，2022-12-01日',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '使用优惠券的减免金额，包含背包中使用优惠券场景，2022-11-30分区生效，2022-12-01日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 45,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619044,
      name: 'consume_num_1d_004',
      fieldExpression: 'consume_num_1d_004',
      sourceFieldName: 'consume_num_1d_004',
      operation: 'SUM',
      displayName:
        '使用背包消费的礼物的数量，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '使用背包消费的礼物的数量，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-01日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 46,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619045,
      name: 'consume_num_1d_003',
      fieldExpression: 'consume_num_1d_003',
      sourceFieldName: 'consume_num_1d_003',
      operation: 'SUM',
      displayName: '使用优惠券消费的礼物数量，2022-11-30分区生效，2022-12-01日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '使用优惠券消费的礼物数量，2022-11-30分区生效，2022-12-01日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 47,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619046,
      name: 'consume_num_1d_001',
      fieldExpression: 'consume_num_1d_001',
      sourceFieldName: 'consume_num_1d_001',
      operation: 'SUM',
      displayName: '最近一天礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '最近一天礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 48,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619047,
      name: 'consume_num_1d_005',
      fieldExpression: 'consume_num_1d_005',
      sourceFieldName: 'consume_num_1d_005',
      operation: 'SUM',
      displayName:
        '最近一天房间内礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '最近一天房间内礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 49,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619048,
      name: 'consume_num_1d_006',
      fieldExpression: 'consume_num_1d_006',
      sourceFieldName: 'consume_num_1d_006',
      operation: 'SUM',
      displayName:
        '最近一天内房间外礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '最近一天内房间外礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 50,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619049,
      name: 'consume_amt_1d_036',
      fieldExpression: 'consume_amt_1d_036',
      sourceFieldName: 'consume_amt_1d_036',
      operation: 'SUM',
      displayName: '直购消费金额，2022-11-30分区生效，2022-12-02日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '直购消费金额，2022-11-30分区生效，2022-12-02日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 51,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619050,
      name: 'consume_num_1d_002',
      fieldExpression: 'consume_num_1d_002',
      sourceFieldName: 'consume_num_1d_002',
      operation: 'SUM',
      displayName: '直购消费数量，2022-11-30分区生效，2022-12-02日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '直购消费数量，2022-11-30分区生效，2022-12-02日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 52,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619051,
      name: 'consume_cnt_1d_035',
      fieldExpression: 'consume_cnt_1d_035',
      sourceFieldName: 'consume_cnt_1d_035',
      operation: 'SUM',
      displayName: '直购消费次数，2022-11-30分区生效，2022-12-02日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '直购消费次数，2022-11-30分区生效，2022-12-02日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 53,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619052,
      name: 'consume_cnt_1d_032',
      fieldExpression: 'consume_cnt_1d_032',
      sourceFieldName: 'consume_cnt_1d_032',
      operation: 'SUM',
      displayName:
        '背包消费次数，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-02日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description:
        '背包消费次数，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-02日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 54,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619053,
      name: 'consume_cnt_1d_031',
      fieldExpression: 'consume_cnt_1d_031',
      sourceFieldName: 'consume_cnt_1d_031',
      operation: 'SUM',
      displayName: '使用优惠券消费次数，2022-11-30分区生效，2022-12-02日生效',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      databaseDataType: 'Int64',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '使用优惠券消费次数，2022-11-30分区生效，2022-12-02日生效',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 55,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619054,
      name: 'testjisuan',
      fieldExpression: '[consume_cnt_1d_001]',
      fieldExpressionTransform: '[consume_cnt_1d_001]',
      sourceFieldName: 'null.dt,null.consume_cnt_1d_001',
      operation: 'SUM',
      displayName: '测试字段计算',
      type: 'ADD',
      category: 'MEASURE',
      dataType: 'NUMBER',
      originDataType: 'NUMBER',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '测试字段计算',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 56,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      computeExpression: '*100',
      summaryMethod: 1,
      dataFormatCode: 0,
    },
    {
      id: 619055,
      name: 'testjisuan_1',
      fieldExpression: '[consume_cnt_1d_001]',
      fieldExpressionTransform: '[consume_cnt_1d_001]',
      sourceFieldName: 'null.dt,null.consume_cnt_1d_001',
      operation: 'SUM',
      displayName: '测试字段计算1',
      type: 'ADD',
      category: 'MEASURE',
      dataType: 'NUMBER',
      dataFormat: 'ORIGINAL',
      customFormatConfig: '{}',
      description: '测试字段计算',
      datasetId: 9478,
      hideStatus: 0,
      sortBy: 57,
      createTime: '2023-09-13 10:29:51',
      updateTime: '2023-09-13 10:29:51',
      dataEnable: 1,
      computeExpression: '+10',
      summaryMethod: 1,
      dataFormatCode: 0,
    },
  ],
  datasources: [
    {
      engine: 'CLICKHOUSE',
      db: 'dws_bban',
      tableName: 'ads_mkt_gift_app_df_dis',
      fields: [
        {
          name: 'dt',
          dataType: 'TIME_YYYYMMDD',
          databaseDataType: 'Date',
          description: '日期，格式为yyyy-mm-dd',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'app_id',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '应用id:1->伴伴,2->皮队友,3->谁是凶手,4->开心玩,6->新冲鸭',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'gift_id',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '礼物id',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'gift_name',
          dataType: 'TEXT',
          databaseDataType: 'String',
          description: '礼物名称',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'gift_price',
          dataType: 'NUMBER',
          databaseDataType: 'Decimal(24, 4)',
          description: '礼物价格，单价：元',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'gift_price_point',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '礼物价格，单价：分',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'gift_type',
          dataType: 'TEXT',
          databaseDataType: 'String',
          description:
            '礼物类型:enum{普通消费礼物(normal),金币消费礼物(coin),金豆消费礼物(bean)}',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'display_situation',
          dataType: 'TEXT',
          databaseDataType: 'String',
          description:
            '展示场景类型:set{房间(room),私聊(chat),订单(order),坐骑(mounts),装扮(decorate)}',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'is_deleted',
          dataType: 'NUMBER',
          databaseDataType: 'Int32',
          description: '是否有效:0-上架,1-下架',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'noble_title_level',
          dataType: 'NUMBER',
          databaseDataType: 'Int32',
          description: '爵位等级',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'first_consume_timestamp',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '礼物首次使用时间戳 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'first_consume_time',
          dataType: 'TEXT',
          databaseDataType: 'String',
          description: '礼物首次使用时间 yy-mm-dd hh:mm:ss [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'last_consume_timestamp',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '礼物最近使用时间戳 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'last_consume_time',
          dataType: 'TEXT',
          databaseDataType: 'String',
          description: '礼物最近使用时间 yy-mm-dd hh:mm:ss [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_user_cnt_da_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计总打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_dst_user_cnt_da_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计总被打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_da_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计总打赏次数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_da_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '历史累计总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_user_cnt_da_002',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计房间内总打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_dst_user_cnt_da_002',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计房间内总被打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_da_002',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计房间内总打赏次数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_da_002',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '历史累计房间内总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_user_cnt_da_003',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计房间外总打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_dst_user_cnt_da_003',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计房间外总被打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_da_003',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '历史累计房间外总打赏次数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_da_003',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '历史累计房间外总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_user_cnt_1d_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天总打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_dst_user_cnt_1d_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天总被打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_1d_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天总打赏次数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_1d_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '最近1天总打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_user_cnt_1d_006',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天房间内打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_dst_user_cnt_1d_002',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天房间内被打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_1d_028',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天房间内打赏次数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_1d_028',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '最近1天房间内打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_user_cnt_1d_007',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天房间外打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_dst_user_cnt_1d_003',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天房间外被打赏人数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_1d_029',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近1天房间外打赏次数 [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_1d_029',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '最近1天房间外打赏金额{单位与礼物类型有关:normal-单位:分} [在对应应用app内]',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_1d_034',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '消耗背包物品总金额，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-01日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'discount_amt_1d_002',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '使用优惠券的减免金额，包含背包中使用优惠券场景，2022-11-30分区生效，2022-12-01日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_num_1d_004',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '使用背包消费的礼物的数量，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-01日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_num_1d_003',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '使用优惠券消费的礼物数量，2022-11-30分区生效，2022-12-01日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_num_1d_001',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '最近一天礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_num_1d_005',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '最近一天房间内礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_num_1d_006',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '最近一天内房间外礼物消费数量，2022-11-30分区生效，2022-12-01日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_amt_1d_036',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '直购消费金额，2022-11-30分区生效，2022-12-02日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_num_1d_002',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '直购消费数量，2022-11-30分区生效，2022-12-02日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_1d_035',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '直购消费次数，2022-11-30分区生效，2022-12-02日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_1d_032',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description:
            '背包消费次数，不包含使用背包中优惠券场景，2022-11-30分区生效，2022-12-02日生效',
          withPermission: true,
          dataEnable: 1,
        },
        {
          name: 'consume_cnt_1d_031',
          dataType: 'NUMBER',
          databaseDataType: 'Int64',
          description: '使用优惠券消费次数，2022-11-30分区生效，2022-12-02日生效',
          withPermission: true,
          dataEnable: 1,
        },
      ],
      dataEnable: 0,
    },
  ],
  validDt: '2023-08-21',
  enableApply: 1,
  group: {
    id: 133,
    name: '001',
    parentId: -1,
    owner: 'hu.dong',
    type: 'ALL',
    position: 'DATASET',
    deleted: 0,
    workspaceId: 7,
    createTime: '2022-06-27 18:22:43',
    updateTime: '2022-06-27 18:22:43',
    absolutePath: '001',
  },
  userResourceRelation: {
    userLevel: 1,
    dataEnable: 1,
    collected: 0,
    applyStatus: 0,
    expired: true,
    role: 'WRITE',
    applying: false,
  },
  dataEnable: 1,
  userLevel: 1,
  collected: 0,
  applyStatus: 0,
}

export const chartJson = {
  id: 8445,
  name: 'test_0914',
  description: '',
  datasetId: 625,
  sql: 'select dt as `619000_` , gift_type as `619002_` , SUM(consume_user_cnt_1d_001) as `619030_SUM` , SUM(consume_user_cnt_1d_007) as `619038_SUM` from dws_bban.ads_mkt_gift_app_df_dis where ( dt >= toDate(subtractDays(now(),30)) and dt <= toDate(subtractDays(now(),1)) ) group by dt , gift_type order by SUM(consume_user_cnt_1d_001) desc limit 1000',
  owner: 'Huang.He@olaola.chat',
  workspaceId: 7,
  chartConfigParam:
    '{"params":{"datasetId":"625","properties":[{"id":619000,"name":"dt","fieldExpression":"dt","sourceFieldName":"dt","operation":"SUM","displayName":"日期，格式为yyyy-mm-dd","category":"PROPERTY","dataType":"TIME_YYYYMMDD","originDataType":"TIME_YYYYMMDD","databaseDataType":"Date","dataFormat":"ORIGINAL","customFormatConfig":"{}","description":"日期，格式为yyyy-mm-dd","datasetId":9478,"hideStatus":0,"sortBy":1,"createTime":"2023-09-13 10:29:50","updateTime":"2023-09-13 10:29:50","dataEnable":1,"summaryMethod":1,"dataFormatCode":0,"showPop":false,"dateGroupType":"","weekForm":"","dateShow":"1"},{"id":619002,"name":"gift_type","fieldExpression":"gift_type","sourceFieldName":"gift_type","operation":"SUM","displayName":"礼物类型:enum{普通消费礼物(nor","category":"PROPERTY","dataType":"TEXT","originDataType":"TEXT","databaseDataType":"String","dataFormat":"ORIGINAL","customFormatConfig":"{}","description":"礼物类型:enum{普通消费礼物(normal),金币消费礼物(coin),金豆消费礼物(bean)}","datasetId":9478,"hideStatus":0,"sortBy":3,"createTime":"2023-09-13 10:29:50","updateTime":"2023-09-13 10:29:50","dataEnable":1,"summaryMethod":1,"dataFormatCode":0,"showPop":false,"dateGroupType":"","weekForm":"","dateShow":"1"}],"MEASUREes":[{"id":619030,"name":"consume_user_cnt_1d_001","fieldExpression":"consume_user_cnt_1d_001","sourceFieldName":"consume_user_cnt_1d_001","operation":"SUM","displayName":"最近1天总打赏人数 [在对应应用app内","category":"MEASURE","dataType":"NUMBER","originDataType":"NUMBER","databaseDataType":"Int64","dataFormat":"ORIGINAL","customFormatConfig":"{}","description":"最近1天总打赏人数 [在对应应用app内]","datasetId":9478,"hideStatus":0,"sortBy":32,"createTime":"2023-09-13 10:29:51","updateTime":"2023-09-13 10:29:51","dataEnable":1,"summaryMethod":1,"dataFormatCode":0,"highLight":false,"showPop":false,"__key__":1694681364134,"MEASURE":0},{"id":619038,"name":"consume_user_cnt_1d_007","fieldExpression":"consume_user_cnt_1d_007","sourceFieldName":"consume_user_cnt_1d_007","operation":"SUM","displayName":"最近1天房间外打赏人数 [在对应应用ap","category":"MEASURE","dataType":"NUMBER","originDataType":"NUMBER","databaseDataType":"Int64","dataFormat":"ORIGINAL","customFormatConfig":"{}","description":"最近1天房间外打赏人数 [在对应应用app内]","datasetId":9478,"hideStatus":0,"sortBy":40,"createTime":"2023-09-13 10:29:51","updateTime":"2023-09-13 10:29:51","dataEnable":1,"summaryMethod":1,"dataFormatCode":0,"highLight":false,"showPop":false,"__key__":1694681475915,"MEASURE":1}],"filters":[{"id":619000,"name":"dt","fieldExpression":"dt","sourceFieldName":"dt","operation":"SUM","displayName":"日期，格式为yyyy-mm-dd","category":"PROPERTY","dataType":"TIME_YYYYMMDD","originDataType":"TIME_YYYYMMDD","databaseDataType":"Date","dataFormat":"ORIGINAL","customFormatConfig":"{}","description":"日期，格式为yyyy-mm-dd","datasetId":9478,"hideStatus":0,"sortBy":1,"createTime":"2023-09-13 10:29:50","updateTime":"2023-09-13 10:29:50","dataEnable":1,"summaryMethod":1,"dataFormatCode":0,"showPop":false,"filterConfig":{"timeType":{"fastChooseParams":"","isDt":true,"filterMethod":"2","intervalType":"3","filterCondition":[{"timePosition":"begin","timeType":"2","date":"","operator":"2","operatorValue":30,"accuracy":"date"},{"timePosition":"end","timeType":"2","date":"","operator":"2","operatorValue":1,"accuracy":"date"}],"validDt":false}},"filterDescribe":"23/08/15 - 23/09/13","__key__":"1694681335668"}]},"config":{"style1":"juzhongduiqi","style2":"budengkuan","chartType":"table","pageSize":20,"chartData":[],"chartFields":[],"contrast":{"status":false,"vsTime":{},"vsFields":[],"content":"0","unity":"0"},"sorts":[{"status":false,"sourceFieldName":"","displayName":"","sortType":"desc","dataNum":50,"MEASURE":""}],"sortFieldConfig":{"prop":"0","order":"ascending"},"floatFieldConfig":[],"clonedData":[["2023-08-17","normal",26982,6288],["2023-08-15","normal",26626,8020],["2023-08-18","normal",25739,7218],["2023-08-16","normal",23139,6723],["2023-08-20","normal",18973,5192],["2023-08-19","normal",17984,4845],["2023-08-21","normal",17758,5143],["2023-08-21","bean",0,0],["2023-08-20","bean",0,0],["2023-08-15","bean",0,0],["2023-08-18","bean",0,0],["2023-08-17","bean",0,0],["2023-08-19","bean",0,0],["2023-08-16","bean",0,0]],"clonedFields":[{"expression":"dt","displayName":"日期，格式为yyyy-mm-dd","sourceFieldName":"dt","category":"PROPERTY","dataType":"TIME_YYYYMMDD","dataFormat":"ORIGINAL","dataFormatCode":0,"params":"{\\"summaryMethod\\":1,\\"displayName\\":\\"日期，格式为yyyy-mm-dd\\",\\"dataFormatCode\\":0,\\"description\\":\\"日期，格式为yyyy-mm-dd\\",\\"dataEnable\\":1,\\"dateShow\\":\\"1\\",\\"fieldExpression\\":\\"dt\\",\\"datasetId\\":9478,\\"sortBy\\":1,\\"id\\":619000,\\"originDataType\\":\\"TIME_YYYYMMDD\\",\\"dataFormat\\":\\"ORIGINAL\\",\\"dataType\\":\\"TIME_YYYYMMDD\\",\\"updateTime\\":\\"2023-09-13 10:29:50\\",\\"showPop\\":false,\\"dateGroupType\\":\\"\\",\\"hideStatus\\":0,\\"createTime\\":\\"2023-09-13 10:29:50\\",\\"sourceFieldName\\":\\"dt\\",\\"name\\":\\"dt\\",\\"weekForm\\":\\"\\",\\"databaseDataType\\":\\"Date\\",\\"customFormatConfig\\":\\"{}\\",\\"category\\":\\"PROPERTY\\",\\"operation\\":\\"SUM\\"}","datasetFieldId":619000,"modifyName":false,"hide":false,"uniqueKey":"619000_"},{"expression":"gift_type","displayName":"礼物类型:enum{普通消费礼物(nor","sourceFieldName":"gift_type","category":"PROPERTY","dataType":"TEXT","dataFormat":"ORIGINAL","dataFormatCode":0,"params":"{\\"summaryMethod\\":1,\\"displayName\\":\\"礼物类型:enum{普通消费礼物(nor\\",\\"dataFormatCode\\":0,\\"description\\":\\"礼物类型:enum{普通消费礼物(normal),金币消费礼物(coin),金豆消费礼物(bean)}\\",\\"dataEnable\\":1,\\"dateShow\\":\\"1\\",\\"fieldExpression\\":\\"gift_type\\",\\"datasetId\\":9478,\\"sortBy\\":3,\\"id\\":619002,\\"originDataType\\":\\"TEXT\\",\\"dataFormat\\":\\"ORIGINAL\\",\\"dataType\\":\\"TEXT\\",\\"updateTime\\":\\"2023-09-13 10:29:50\\",\\"showPop\\":false,\\"dateGroupType\\":\\"\\",\\"hideStatus\\":0,\\"createTime\\":\\"2023-09-13 10:29:50\\",\\"sourceFieldName\\":\\"gift_type\\",\\"name\\":\\"gift_type\\",\\"weekForm\\":\\"\\",\\"databaseDataType\\":\\"String\\",\\"customFormatConfig\\":\\"{}\\",\\"category\\":\\"PROPERTY\\",\\"operation\\":\\"SUM\\"}","datasetFieldId":619002,"modifyName":false,"hide":false,"uniqueKey":"619002_"},{"expression":"SUM(consume_user_cnt_1d_001)","operation":"SUM","displayName":"最近1天总打赏人数 [在对应应用app内","sourceFieldName":"consume_user_cnt_1d_001","category":"MEASURE","dataType":"NUMBER","dataFormat":"ORIGINAL","dataFormatCode":0,"params":"{\\"__key__\\":1694681364134,\\"summaryMethod\\":1,\\"displayName\\":\\"最近1天总打赏人数 [在对应应用app内\\",\\"dataFormatCode\\":0,\\"description\\":\\"最近1天总打赏人数 [在对应应用app内]\\",\\"dataEnable\\":1,\\"fieldExpression\\":\\"consume_user_cnt_1d_001\\",\\"datasetId\\":9478,\\"sortBy\\":32,\\"id\\":619030,\\"originDataType\\":\\"NUMBER\\",\\"dataFormat\\":\\"ORIGINAL\\",\\"dataType\\":\\"NUMBER\\",\\"MEASURE\\":0,\\"updateTime\\":\\"2023-09-13 10:29:51\\",\\"showPop\\":false,\\"hideStatus\\":0,\\"createTime\\":\\"2023-09-13 10:29:51\\",\\"sourceFieldName\\":\\"consume_user_cnt_1d_001\\",\\"highLight\\":false,\\"name\\":\\"consume_user_cnt_1d_001\\",\\"databaseDataType\\":\\"Int64\\",\\"customFormatConfig\\":\\"{}\\",\\"category\\":\\"MEASURE\\",\\"operation\\":\\"SUM\\"}","datasetFieldId":619030,"modifyName":false,"hide":false,"uniqueKey":"619030_SUM"},{"expression":"SUM(consume_user_cnt_1d_007)","operation":"SUM","displayName":"最近1天房间外打赏人数 [在对应应用ap","sourceFieldName":"consume_user_cnt_1d_007","category":"MEASURE","dataType":"NUMBER","dataFormat":"ORIGINAL","dataFormatCode":0,"params":"{\\"__key__\\":1694681475915,\\"summaryMethod\\":1,\\"displayName\\":\\"最近1天房间外打赏人数 [在对应应用ap\\",\\"dataFormatCode\\":0,\\"description\\":\\"最近1天房间外打赏人数 [在对应应用app内]\\",\\"dataEnable\\":1,\\"fieldExpression\\":\\"consume_user_cnt_1d_007\\",\\"datasetId\\":9478,\\"sortBy\\":40,\\"id\\":619038,\\"originDataType\\":\\"NUMBER\\",\\"dataFormat\\":\\"ORIGINAL\\",\\"dataType\\":\\"NUMBER\\",\\"MEASURE\\":1,\\"updateTime\\":\\"2023-09-13 10:29:51\\",\\"showPop\\":false,\\"hideStatus\\":0,\\"createTime\\":\\"2023-09-13 10:29:51\\",\\"sourceFieldName\\":\\"consume_user_cnt_1d_007\\",\\"highLight\\":false,\\"name\\":\\"consume_user_cnt_1d_007\\",\\"databaseDataType\\":\\"Int64\\",\\"customFormatConfig\\":\\"{}\\",\\"category\\":\\"MEASURE\\",\\"operation\\":\\"SUM\\"}","datasetFieldId":619038,"modifyName":false,"hide":false,"uniqueKey":"619038_SUM"}],"setting":{"axis":[{"id":619030,"name":"consume_user_cnt_1d_001","fieldExpression":"consume_user_cnt_1d_001","sourceFieldName":"consume_user_cnt_1d_001","operation":"SUM","displayName":"最近1天总打赏人数 [在对应应用app内","category":"MEASURE","dataType":"NUMBER","originDataType":"NUMBER","databaseDataType":"Int64","dataFormat":"ORIGINAL","customFormatConfig":"{}","description":"最近1天总打赏人数 [在对应应用app内]","datasetId":9478,"hideStatus":0,"sortBy":32,"createTime":"2023-09-13 10:29:51","updateTime":"2023-09-13 10:29:51","dataEnable":1,"summaryMethod":1,"dataFormatCode":0,"highLight":false,"showPop":false,"__key__":1694681364134,"yAxisPosition":"left","chartType":"table"},{"id":619038,"name":"consume_user_cnt_1d_007","fieldExpression":"consume_user_cnt_1d_007","sourceFieldName":"consume_user_cnt_1d_007","operation":"SUM","displayName":"最近1天房间外打赏人数 [在对应应用ap","category":"MEASURE","dataType":"NUMBER","originDataType":"NUMBER","databaseDataType":"Int64","dataFormat":"ORIGINAL","customFormatConfig":"{}","description":"最近1天房间外打赏人数 [在对应应用app内]","datasetId":9478,"hideStatus":0,"sortBy":40,"createTime":"2023-09-13 10:29:51","updateTime":"2023-09-13 10:29:51","dataEnable":1,"summaryMethod":1,"dataFormatCode":0,"highLight":false,"showPop":false,"__key__":1694681475915,"yAxisPosition":"left","chartType":"table"}]}}}',
  createTime: '2023-09-14 16:50:56',
  updateTime: '2023-09-14 16:52:07',
  dataEnable: 1,
  userLevel: 1,
  collected: 0,
  ownerChinesName: '黄河(六零)',
  userResourceRelation: {
    userLevel: 1,
    dataEnable: 1,
    collected: 0,
    applyStatus: 0,
    applying: false,
  },
  dataset: {
    id: 174,
    name: '测试新建数据集050401',
    description: '',
    version: 30,
    lastEditVersion: 30,
    versionId: 174,
    realId: 420,
    creator: 'hu.dong@olaola.chat',
    operator: 'bi-li.huifang',
    docUrl: '',
    workspaceId: 7,
    status: 'ONLINE',
    createTime: '2023-05-04 14:03:32',
    updateTime: '2023-09-12 17:58:34',
    creatorChinesName: '胡东(弥彦)',
    operatorChinesName: '李慧芳(南枫)',
    groupId: 161,
    fields: [
      {
        id: 654701,
        name: 'project_name',
        fieldExpression: 'project_name',
        sourceFieldName: 'project_name',
        operation: 'SUM',
        displayName: '项目名称',
        category: 'PROPERTY',
        dataType: 'TEXT',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: '项目名称',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 1,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654702,
        name: 'sprint_start_date',
        fieldExpression: 'sprint_start_date',
        sourceFieldName: 'sprint_start_date',
        operation: 'SUM',
        displayName: '迭代开始日期',
        category: 'PROPERTY',
        dataType: 'TEXT',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: '迭代开始日期',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 2,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654703,
        name: 'sprint_end_date',
        fieldExpression: 'sprint_end_date',
        sourceFieldName: 'sprint_end_date',
        operation: 'SUM',
        displayName: '迭代结束日期',
        category: 'PROPERTY',
        dataType: 'TEXT',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: '迭代结束日期',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 3,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654704,
        name: 'story_title_name',
        fieldExpression: 'story_title_name',
        sourceFieldName: 'story_title_name',
        operation: 'SUM',
        displayName: 'story标题',
        category: 'PROPERTY',
        dataType: 'TEXT',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: 'story标题',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 4,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654705,
        name: 'task_title_name',
        fieldExpression: 'task_title_name',
        sourceFieldName: 'task_title_name',
        operation: 'SUM',
        displayName: 'story关联的task标题',
        category: 'PROPERTY',
        dataType: 'TEXT',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: 'story关联的task标题',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 5,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654706,
        name: 'dt',
        fieldExpression: 'dt',
        sourceFieldName: 'dt',
        operation: 'SUM',
        displayName: '日期,格式为yyyy-MM-dd',
        category: 'PROPERTY',
        dataType: 'TIME_YYYYMMDD',
        originDataType: 'TIME_YYYYMMDD',
        databaseDataType: 'Date',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: '日期,格式为yyyy-MM-dd',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 6,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654707,
        name: 'task_github_sid',
        fieldExpression: 'task_github_sid',
        sourceFieldName: 'task_github_sid',
        operation: 'SUM',
        displayName: 'story关联的task编号,issue唯一id',
        category: 'PROPERTY',
        dataType: 'NUMBER',
        originDataType: 'NUMBER',
        databaseDataType: 'Int64',
        dataFormat: 'DECIMAL_2',
        customFormatConfig: '{}',
        description: 'story关联的task编号,issue唯一id',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 7,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 3,
      },
      {
        id: 654708,
        name: 'labels',
        fieldExpression: 'labels',
        sourceFieldName: 'labels',
        operation: 'SUM',
        displayName: '业务方，github-labels字段内容,多个以英文逗号分隔',
        category: 'PROPERTY',
        dataType: 'TEXT',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: '业务方，github-labels字段内容,多个以英文逗号分隔',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 8,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654709,
        name: 'story_github_sid',
        fieldExpression: 'story_github_sid',
        sourceFieldName: 'story_github_sid',
        operation: 'SUM',
        displayName: 'story的issue唯一id',
        category: 'PROPERTY',
        dataType: 'NUMBER',
        originDataType: 'NUMBER',
        databaseDataType: 'Int64',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: 'story的issue唯一id',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 9,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654710,
        name: 'sprint_span',
        fieldExpression: "concat(sprint_start_date,'~',sprint_end_date)",
        fieldExpressionTransform: "concat(sprint_start_date,'~',sprint_end_date)",
        sourceFieldName: '',
        operation: 'SUM',
        displayName: '迭代区间',
        type: 'ADD',
        category: 'PROPERTY',
        dataType: 'TEXT',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: '迭代区间',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 10,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        computeExpression: '',
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654711,
        name: 'is_current_spring',
        fieldExpression:
          "case when toDate(case when sprint_start_date='' then '1970-01-01' else sprint_start_date end)<=today()-1 and toDate(case when sprint_end_date='' then '1970-01-01' else sprint_end_date end)>=today()-1 then 1 else 0 end",
        fieldExpressionTransform:
          "case when toDate(case when sprint_start_date='' then '1970-01-01' else sprint_start_date end)<=today()-1 and toDate(case when sprint_end_date='' then '1970-01-01' else sprint_end_date end)>=today()-1 then 1 else 0 end",
        sourceFieldName: '',
        operation: 'SUM',
        displayName: '是否当前迭代',
        type: 'ADD',
        category: 'PROPERTY',
        dataType: 'TEXT',
        dataFormat: 'ORIGINAL',
        customFormatConfig: '{}',
        description: '是否当前迭代',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 11,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        computeExpression: '',
        summaryMethod: 1,
        dataFormatCode: 0,
      },
      {
        id: 654712,
        name: 'plan_point',
        fieldExpression: 'toFloat64OrNull(plan_point)',
        sourceFieldName: 'plan_point',
        operation: 'SUM',
        displayName: 'story关联的task计划工时',
        category: 'MEASURE',
        dataType: 'NUMBER',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'DECIMAL_2',
        customFormatConfig: '{}',
        description: 'story关联的task计划工时',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 13,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 3,
      },
      {
        id: 654713,
        name: 'remain_point',
        fieldExpression: 'toFloat64OrNull(remain_point)',
        sourceFieldName: 'remain_point',
        operation: 'SUM',
        displayName: 'story关联的task剩余工时',
        category: 'MEASURE',
        dataType: 'NUMBER',
        originDataType: 'TEXT',
        databaseDataType: 'String',
        dataFormat: 'DECIMAL_2',
        customFormatConfig: '{}',
        description: 'story关联的task剩余工时',
        datasetId: 9948,
        hideStatus: 0,
        sortBy: 14,
        createTime: '2023-09-27 18:17:36',
        updateTime: '2023-09-27 18:17:36',
        dataEnable: 1,
        summaryMethod: 1,
        dataFormatCode: 3,
      },
    ],
    datasources: [
      {
        engine: 'CLICKHOUSE',
        db: 'dws_haddock',
        tableName: 'ads_project_report_cache_dis',
        fields: [
          {
            name: 'dt',
            dataType: 'TIME_YYYYMMDD',
            databaseDataType: 'Date',
            description: '日期，yyyy-MM-dd',
            withPermission: true,
            dataEnable: 1,
          },
          {
            name: 'project_id',
            dataType: 'NUMBER',
            databaseDataType: 'Int32',
            description: '项目ID',
            withPermission: true,
            dataEnable: 1,
          },
          {
            name: 'report_id',
            dataType: 'NUMBER',
            databaseDataType: 'Int32',
            description: '报表ID',
            withPermission: true,
            dataEnable: 1,
          },
          {
            name: 'sql',
            dataType: 'TEXT',
            databaseDataType: 'String',
            description: 'sql',
            withPermission: true,
            dataEnable: 1,
          },
          {
            name: 'sql_md5',
            dataType: 'TEXT',
            databaseDataType: 'String',
            description: '条件生成的md5',
            withPermission: true,
            dataEnable: 1,
          },
          {
            name: 'json',
            dataType: 'TEXT',
            databaseDataType: 'SimpleAggregateFunction(anyLast, String)',
            description: '结果数据',
            withPermission: true,
            dataEnable: 1,
          },
          {
            name: 'creator',
            dataType: 'TEXT',
            databaseDataType: 'String',
            description: '创建人',
            withPermission: true,
            dataEnable: 1,
          },
          {
            name: 'create_time',
            dataType: 'TEXT',
            databaseDataType: 'SimpleAggregateFunction(anyLast, DateTime)',
            description: '创建时间',
            withPermission: true,
            dataEnable: 1,
          },
        ],
        dataEnable: 0,
      },
    ],
    validDt: '2023-10-17',
    enableApply: 1,
    group: {
      id: 161,
      name: '123',
      parentId: -1,
      owner: 'bi-li.huifang',
      type: 'ALL',
      position: 'DATASET',
      deleted: 0,
      workspaceId: 7,
      createTime: '2023-05-04 14:00:14',
      updateTime: '2023-05-04 14:00:14',
      absolutePath: '123',
    },
    userResourceRelation: {
      userLevel: 1,
      dataEnable: 1,
      collected: 0,
      applyStatus: 0,
      expired: false,
      role: 'WRITE',
      applying: false,
    },
    collected: 0,
    applyStatus: 0,
    dataEnable: 1,
    userLevel: 1,
  },
  properties: [
    {
      summaryMethod: 1,
      displayName: '日期，格式为yyyy-mm-dd',
      dataFormatCode: 0,
      description: '日期，格式为yyyy-mm-dd',
      dataEnable: 1,
      dateShow: '1',
      fieldExpression: 'dt',
      datasetId: 9478,
      sortBy: 1,
      id: 619000,
      originDataType: 'TIME_YYYYMMDD',
      dataFormat: 'ORIGINAL',
      dataType: 'TIME_YYYYMMDD',
      updateTime: '2023-09-13 10:29:50',
      showPop: false,
      dateGroupType: '',
      hideStatus: 0,
      createTime: '2023-09-13 10:29:50',
      sourceFieldName: 'dt',
      name: 'dt',
      weekForm: '',
      databaseDataType: 'Date',
      customFormatConfig: '{}',
      category: 'PROPERTY',
      operation: 'SUM',
    },
    {
      summaryMethod: 1,
      displayName: '礼物类型:enum{普通消费礼物(nor',
      dataFormatCode: 0,
      description:
        '礼物类型:enum{普通消费礼物(normal),金币消费礼物(coin),金豆消费礼物(bean)}',
      dataEnable: 1,
      dateShow: '1',
      fieldExpression: 'gift_type',
      datasetId: 9478,
      sortBy: 3,
      id: 619002,
      originDataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      dataType: 'TEXT',
      updateTime: '2023-09-13 10:29:50',
      showPop: false,
      dateGroupType: '',
      hideStatus: 0,
      createTime: '2023-09-13 10:29:50',
      sourceFieldName: 'gift_type',
      name: 'gift_type',
      weekForm: '',
      databaseDataType: 'String',
      customFormatConfig: '{}',
      category: 'PROPERTY',
      operation: 'SUM',
    },
  ],
  indexes: [
    {
      __key__: 1694681364134,
      summaryMethod: 1,
      displayName: '最近1天总打赏人数 [在对应应用app内',
      dataFormatCode: 0,
      description: '最近1天总打赏人数 [在对应应用app内]',
      dataEnable: 1,
      fieldExpression: 'consume_user_cnt_1d_001',
      datasetId: 9478,
      sortBy: 32,
      id: 619030,
      originDataType: 'NUMBER',
      dataFormat: 'ORIGINAL',
      dataType: 'NUMBER',
      index: 0,
      updateTime: '2023-09-13 10:29:51',
      showPop: false,
      hideStatus: 0,
      createTime: '2023-09-13 10:29:51',
      sourceFieldName: 'consume_user_cnt_1d_001',
      highLight: false,
      name: 'consume_user_cnt_1d_001',
      databaseDataType: 'Int64',
      customFormatConfig: '{}',
      category: 'MEASURE',
      operation: 'SUM',
    },
    {
      __key__: 1694681475915,
      summaryMethod: 1,
      displayName: '最近1天房间外打赏人数 [在对应应用ap',
      dataFormatCode: 0,
      description: '最近1天房间外打赏人数 [在对应应用app内]',
      dataEnable: 1,
      fieldExpression: 'consume_user_cnt_1d_007',
      datasetId: 9478,
      sortBy: 40,
      id: 619038,
      originDataType: 'NUMBER',
      dataFormat: 'ORIGINAL',
      dataType: 'NUMBER',
      index: 1,
      updateTime: '2023-09-13 10:29:51',
      showPop: false,
      hideStatus: 0,
      createTime: '2023-09-13 10:29:51',
      sourceFieldName: 'consume_user_cnt_1d_007',
      highLight: false,
      name: 'consume_user_cnt_1d_007',
      databaseDataType: 'Int64',
      customFormatConfig: '{}',
      category: 'MEASURE',
      operation: 'SUM',
    },
  ],
  filters: [
    {
      __key__: '1694681335668',
      summaryMethod: 1,
      displayName: '日期，格式为yyyy-mm-dd',
      dataFormatCode: 0,
      description: '日期，格式为yyyy-mm-dd',
      filterConfig: {
        timeType: {
          fastChooseParams: '',
          filterMethod: '2',
          intervalType: '3',
          validDt: false,
          filterCondition: [
            {
              date: '',
              timePosition: 'begin',
              timeType: '2',
              accuracy: 'date',
              operator: '2',
              operatorValue: 30,
            },
            {
              date: '',
              timePosition: 'end',
              timeType: '2',
              accuracy: 'date',
              operator: '2',
              operatorValue: 1,
            },
          ],
          isDt: true,
        },
      },
      filterDescribe: '23/08/15 - 23/09/13',
      dataEnable: 1,
      fieldExpression: 'dt',
      datasetId: 9478,
      sortBy: 1,
      id: 619000,
      originDataType: 'TIME_YYYYMMDD',
      dataFormat: 'ORIGINAL',
      dataType: 'TIME_YYYYMMDD',
      updateTime: '2023-09-13 10:29:50',
      showPop: false,
      hideStatus: 0,
      createTime: '2023-09-13 10:29:50',
      sourceFieldName: 'dt',
      name: 'dt',
      databaseDataType: 'Date',
      customFormatConfig: '{}',
      category: 'PROPERTY',
      operation: 'SUM',
    },
  ],
  chartConfig: {
    params: {
      indexes: [
        {
          __key__: 1694681364134,
          summaryMethod: 1,
          displayName: '最近1天总打赏人数 [在对应应用app内',
          dataFormatCode: 0,
          description: '最近1天总打赏人数 [在对应应用app内]',
          dataEnable: 1,
          fieldExpression: 'consume_user_cnt_1d_001',
          datasetId: 9478,
          sortBy: 32,
          id: 619030,
          originDataType: 'NUMBER',
          dataFormat: 'ORIGINAL',
          dataType: 'NUMBER',
          index: 0,
          updateTime: '2023-09-13 10:29:51',
          showPop: false,
          hideStatus: 0,
          createTime: '2023-09-13 10:29:51',
          sourceFieldName: 'consume_user_cnt_1d_001',
          highLight: false,
          name: 'consume_user_cnt_1d_001',
          databaseDataType: 'Int64',
          customFormatConfig: '{}',
          category: 'MEASURE',
          operation: 'SUM',
        },
        {
          __key__: 1694681475915,
          summaryMethod: 1,
          displayName: '最近1天房间外打赏人数 [在对应应用ap',
          dataFormatCode: 0,
          description: '最近1天房间外打赏人数 [在对应应用app内]',
          dataEnable: 1,
          fieldExpression: 'consume_user_cnt_1d_007',
          datasetId: 9478,
          sortBy: 40,
          id: 619038,
          originDataType: 'NUMBER',
          dataFormat: 'ORIGINAL',
          dataType: 'NUMBER',
          index: 1,
          updateTime: '2023-09-13 10:29:51',
          showPop: false,
          hideStatus: 0,
          createTime: '2023-09-13 10:29:51',
          sourceFieldName: 'consume_user_cnt_1d_007',
          highLight: false,
          name: 'consume_user_cnt_1d_007',
          databaseDataType: 'Int64',
          customFormatConfig: '{}',
          category: 'MEASURE',
          operation: 'SUM',
        },
      ],
      datasetId: '625',
      filters: [
        {
          __key__: '1694681335668',
          summaryMethod: 1,
          displayName: '日期，格式为yyyy-mm-dd',
          dataFormatCode: 0,
          description: '日期，格式为yyyy-mm-dd',
          filterConfig: {
            timeType: {
              fastChooseParams: '',
              filterMethod: '2',
              intervalType: '3',
              validDt: false,
              filterCondition: [
                {
                  date: '',
                  timePosition: 'begin',
                  timeType: '2',
                  accuracy: 'date',
                  operator: '2',
                  operatorValue: 30,
                },
                {
                  date: '',
                  timePosition: 'end',
                  timeType: '2',
                  accuracy: 'date',
                  operator: '2',
                  operatorValue: 1,
                },
              ],
              isDt: true,
            },
          },
          filterDescribe: '23/08/15 - 23/09/13',
          dataEnable: 1,
          fieldExpression: 'dt',
          datasetId: 9478,
          sortBy: 1,
          id: 619000,
          originDataType: 'TIME_YYYYMMDD',
          dataFormat: 'ORIGINAL',
          dataType: 'TIME_YYYYMMDD',
          updateTime: '2023-09-13 10:29:50',
          showPop: false,
          hideStatus: 0,
          createTime: '2023-09-13 10:29:50',
          sourceFieldName: 'dt',
          name: 'dt',
          databaseDataType: 'Date',
          customFormatConfig: '{}',
          category: 'PROPERTY',
          operation: 'SUM',
        },
      ],
      properties: [
        {
          summaryMethod: 1,
          displayName: '日期，格式为yyyy-mm-dd',
          dataFormatCode: 0,
          description: '日期，格式为yyyy-mm-dd',
          dataEnable: 1,
          dateShow: '1',
          fieldExpression: 'dt',
          datasetId: 9478,
          sortBy: 1,
          id: 619000,
          originDataType: 'TIME_YYYYMMDD',
          dataFormat: 'ORIGINAL',
          dataType: 'TIME_YYYYMMDD',
          updateTime: '2023-09-13 10:29:50',
          showPop: false,
          dateGroupType: '',
          hideStatus: 0,
          createTime: '2023-09-13 10:29:50',
          sourceFieldName: 'dt',
          name: 'dt',
          weekForm: '',
          databaseDataType: 'Date',
          customFormatConfig: '{}',
          category: 'PROPERTY',
          operation: 'SUM',
        },
        {
          summaryMethod: 1,
          displayName: '礼物类型:enum{普通消费礼物(nor',
          dataFormatCode: 0,
          description:
            '礼物类型:enum{普通消费礼物(normal),金币消费礼物(coin),金豆消费礼物(bean)}',
          dataEnable: 1,
          dateShow: '1',
          fieldExpression: 'gift_type',
          datasetId: 9478,
          sortBy: 3,
          id: 619002,
          originDataType: 'TEXT',
          dataFormat: 'ORIGINAL',
          dataType: 'TEXT',
          updateTime: '2023-09-13 10:29:50',
          showPop: false,
          dateGroupType: '',
          hideStatus: 0,
          createTime: '2023-09-13 10:29:50',
          sourceFieldName: 'gift_type',
          name: 'gift_type',
          weekForm: '',
          databaseDataType: 'String',
          customFormatConfig: '{}',
          category: 'PROPERTY',
          operation: 'SUM',
        },
      ],
    },
    config: {
      clonedData: [
        ['2023-08-17', 'normal', 26982, 6288],
        ['2023-08-15', 'normal', 26626, 8020],
        ['2023-08-18', 'normal', 25739, 7218],
        ['2023-08-16', 'normal', 23139, 6723],
        ['2023-08-20', 'normal', 18973, 5192],
        ['2023-08-19', 'normal', 17984, 4845],
        ['2023-08-21', 'normal', 17758, 5143],
        ['2023-08-21', 'bean', 0, 0],
        ['2023-08-20', 'bean', 0, 0],
        ['2023-08-15', 'bean', 0, 0],
        ['2023-08-18', 'bean', 0, 0],
        ['2023-08-17', 'bean', 0, 0],
        ['2023-08-19', 'bean', 0, 0],
        ['2023-08-16', 'bean', 0, 0],
      ],
      pageSize: 20,
      chartFields: [],
      setting: {
        axis: [
          {
            __key__: 1694681364134,
            yAxisPosition: 'left',
            summaryMethod: 1,
            displayName: '最近1天总打赏人数 [在对应应用app内',
            dataFormatCode: 0,
            description: '最近1天总打赏人数 [在对应应用app内]',
            dataEnable: 1,
            fieldExpression: 'consume_user_cnt_1d_001',
            datasetId: 9478,
            sortBy: 32,
            id: 619030,
            originDataType: 'NUMBER',
            dataFormat: 'ORIGINAL',
            dataType: 'NUMBER',
            updateTime: '2023-09-13 10:29:51',
            showPop: false,
            hideStatus: 0,
            createTime: '2023-09-13 10:29:51',
            sourceFieldName: 'consume_user_cnt_1d_001',
            highLight: false,
            name: 'consume_user_cnt_1d_001',
            chartType: 'table',
            databaseDataType: 'Int64',
            customFormatConfig: '{}',
            category: 'MEASURE',
            operation: 'SUM',
          },
          {
            __key__: 1694681475915,
            yAxisPosition: 'left',
            summaryMethod: 1,
            displayName: '最近1天房间外打赏人数 [在对应应用ap',
            dataFormatCode: 0,
            description: '最近1天房间外打赏人数 [在对应应用app内]',
            dataEnable: 1,
            fieldExpression: 'consume_user_cnt_1d_007',
            datasetId: 9478,
            sortBy: 40,
            id: 619038,
            originDataType: 'NUMBER',
            dataFormat: 'ORIGINAL',
            dataType: 'NUMBER',
            updateTime: '2023-09-13 10:29:51',
            showPop: false,
            hideStatus: 0,
            createTime: '2023-09-13 10:29:51',
            sourceFieldName: 'consume_user_cnt_1d_007',
            highLight: false,
            name: 'consume_user_cnt_1d_007',
            chartType: 'table',
            databaseDataType: 'Int64',
            customFormatConfig: '{}',
            category: 'MEASURE',
            operation: 'SUM',
          },
        ],
      },
      chartData: [],
      sortFieldConfig: {
        prop: '0',
        order: 'ascending',
      },
      contrast: {
        unity: '0',
        vsTime: {},
        vsFields: [],
        content: '0',
        status: false,
      },
      style1: 'juzhongduiqi',
      chartType: 'table',
      floatFieldConfig: [],
      style2: 'budengkuan',
      sorts: [
        {
          sortType: 'desc',
          sourceFieldName: '',
          displayName: '',
          dataNum: 50,
          index: '',
          status: false,
        },
      ],
      clonedFields: [
        {
          hide: false,
          expression: 'dt',
          modifyName: false,
          displayName: '日期，格式为yyyy-mm-dd',
          sourceFieldName: 'dt',
          dataFormat: 'ORIGINAL',
          dataType: 'TIME_YYYYMMDD',
          uniqueKey: '619000_',
          dataFormatCode: 0,
          datasetFieldId: 619000,
          category: 'PROPERTY',
          params:
            '{"summaryMethod":1,"displayName":"日期，格式为yyyy-mm-dd","dataFormatCode":0,"description":"日期，格式为yyyy-mm-dd","dataEnable":1,"dateShow":"1","fieldExpression":"dt","datasetId":9478,"sortBy":1,"id":619000,"originDataType":"TIME_YYYYMMDD","dataFormat":"ORIGINAL","dataType":"TIME_YYYYMMDD","updateTime":"2023-09-13 10:29:50","showPop":false,"dateGroupType":"","hideStatus":0,"createTime":"2023-09-13 10:29:50","sourceFieldName":"dt","name":"dt","weekForm":"","databaseDataType":"Date","customFormatConfig":"{}","category":"PROPERTY","operation":"SUM"}',
        },
        {
          hide: false,
          expression: 'gift_type',
          modifyName: false,
          displayName: '礼物类型:enum{普通消费礼物(nor',
          sourceFieldName: 'gift_type',
          dataFormat: 'ORIGINAL',
          dataType: 'TEXT',
          uniqueKey: '619002_',
          dataFormatCode: 0,
          datasetFieldId: 619002,
          category: 'PROPERTY',
          params:
            '{"summaryMethod":1,"displayName":"礼物类型:enum{普通消费礼物(nor","dataFormatCode":0,"description":"礼物类型:enum{普通消费礼物(normal),金币消费礼物(coin),金豆消费礼物(bean)}","dataEnable":1,"dateShow":"1","fieldExpression":"gift_type","datasetId":9478,"sortBy":3,"id":619002,"originDataType":"TEXT","dataFormat":"ORIGINAL","dataType":"TEXT","updateTime":"2023-09-13 10:29:50","showPop":false,"dateGroupType":"","hideStatus":0,"createTime":"2023-09-13 10:29:50","sourceFieldName":"gift_type","name":"gift_type","weekForm":"","databaseDataType":"String","customFormatConfig":"{}","category":"PROPERTY","operation":"SUM"}',
        },
        {
          expression: 'SUM(consume_user_cnt_1d_001)',
          displayName: '最近1天总打赏人数 [在对应应用app内',
          dataFormat: 'ORIGINAL',
          dataType: 'NUMBER',
          uniqueKey: '619030_SUM',
          dataFormatCode: 0,
          datasetFieldId: 619030,
          params:
            '{"__key__":1694681364134,"summaryMethod":1,"displayName":"最近1天总打赏人数 [在对应应用app内","dataFormatCode":0,"description":"最近1天总打赏人数 [在对应应用app内]","dataEnable":1,"fieldExpression":"consume_user_cnt_1d_001","datasetId":9478,"sortBy":32,"id":619030,"originDataType":"NUMBER","dataFormat":"ORIGINAL","dataType":"NUMBER","index":0,"updateTime":"2023-09-13 10:29:51","showPop":false,"hideStatus":0,"createTime":"2023-09-13 10:29:51","sourceFieldName":"consume_user_cnt_1d_001","highLight":false,"name":"consume_user_cnt_1d_001","databaseDataType":"Int64","customFormatConfig":"{}","category":"MEASURE","operation":"SUM"}',
          hide: false,
          modifyName: false,
          sourceFieldName: 'consume_user_cnt_1d_001',
          category: 'MEASURE',
          operation: 'SUM',
        },
        {
          expression: 'SUM(consume_user_cnt_1d_007)',
          displayName: '最近1天房间外打赏人数 [在对应应用ap',
          dataFormat: 'ORIGINAL',
          dataType: 'NUMBER',
          uniqueKey: '619038_SUM',
          dataFormatCode: 0,
          datasetFieldId: 619038,
          params:
            '{"__key__":1694681475915,"summaryMethod":1,"displayName":"最近1天房间外打赏人数 [在对应应用ap","dataFormatCode":0,"description":"最近1天房间外打赏人数 [在对应应用app内]","dataEnable":1,"fieldExpression":"consume_user_cnt_1d_007","datasetId":9478,"sortBy":40,"id":619038,"originDataType":"NUMBER","dataFormat":"ORIGINAL","dataType":"NUMBER","index":1,"updateTime":"2023-09-13 10:29:51","showPop":false,"hideStatus":0,"createTime":"2023-09-13 10:29:51","sourceFieldName":"consume_user_cnt_1d_007","highLight":false,"name":"consume_user_cnt_1d_007","databaseDataType":"Int64","customFormatConfig":"{}","category":"MEASURE","operation":"SUM"}',
          hide: false,
          modifyName: false,
          sourceFieldName: 'consume_user_cnt_1d_007',
          category: 'MEASURE',
          operation: 'SUM',
        },
      ],
    },
  },
}

export const queryJson = {
  data: [
    ['2023-10-18~2023-10-31', 'A', 55, 55],
    ['2023-10-20~2023-11-02', 'B', 6, 6],
  ],

  compare: {
    type: 'CHAIN',
    timeField: {
      displayName: '时间',
      name: 'dt',
      category: 'DIMENSION',
    },
    measures: [
      {
        name: 'story_title_name',
        displayName: '总打赏人数',
      },
    ],
  },
  fields: [
    {
      expression: "concat(sprint_start_date,'~',sprint_end_date)",
      displayName: '时间',
      name: 'dt',
      category: 'DIMENSION',
      dataType: 'TIME',
      dataFormat: 'ORIGINAL',
      dataFormatCode: 0,
      params:
        '{"summaryMethod":1,"displayName":"迭代区间","dataFormatCode":0,"description":"迭代区间","type":"ADD","dataEnable":1,"dateShow":"1","fieldExpression":"concat(sprint_start_date,\'~\',sprint_end_date)","datasetId":9948,"sortBy":10,"id":654710,"computeExpression":"","dataFormat":"ORIGINAL","dataType":"TEXT","updateTime":"2023-09-27 18:17:36","showPop":false,"dateGroupType":"","hideStatus":0,"createTime":"2023-09-27 18:17:36","name":"","name":"sprint_span","weekForm":"","fieldExpressionTransform":"concat(sprint_start_date,\'~\',sprint_end_date)","customFormatConfig":"{}","category":"DIMENSION","operation":"SUM"}',
      datasetFieldId: 654710,
      modifyName: false,
      hide: false,
      uniqueKey: '654710_',
    },
    {
      expression: 'project_name',
      displayName: '项目名称',
      name: 'project_name',
      category: 'DIMENSION',
      dataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      dataFormatCode: 0,
      params:
        '{"summaryMethod":1,"displayName":"项目名称","dataFormatCode":0,"description":"项目名称","dataEnable":1,"dateShow":1,"fieldExpression":"project_name","datasetId":9948,"sortBy":1,"id":654701,"originDataType":"TEXT","dataFormat":"ORIGINAL","dataType":"TEXT","updateTime":"2023-09-27 18:17:36","showPop":false,"dateGroupType":"","hideStatus":0,"createTime":"2023-09-27 18:17:36","name":"project_name","name":"project_name","weekForm":"","databaseDataType":"String","customFormatConfig":"{}","category":"DIMENSION","operation":"SUM"}',
      datasetFieldId: 654701,
      modifyName: false,
      hide: false,
      uniqueKey: '654701_',
    },
    {
      expression: 'COUNT(story_title_name)',
      operation: 'COUNT',
      displayName: 'story标题',
      name: 'story_title_name',
      category: 'MEASURE',
      dataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      dataFormatCode: 0,
      params:
        '{"__key__":1697788371022,"originDataType":"TEXT","summaryMethod":"6","displayName":"story标题","dataFormat":"ORIGINAL","dataType":"TEXT","dataFormatCode":0,"description":"story标题","updateTime":"2023-09-27 18:17:36","showPop":false,"dataEnable":1,"hideStatus":0,"createTime":"2023-09-27 18:17:36","name":"story_title_name","name":"story_title_name","fieldExpression":"story_title_name","databaseDataType":"String","datasetId":9948,"sortBy":4,"id":654704,"customFormatConfig":"{}","category":"PROPERTY","operation":"SUM"}',
      datasetFieldId: 654704,
      modifyName: false,
      hide: false,
      uniqueKey: '654704_COUNT',
    },
    {
      expression: 'COUNT(task_title_name)',
      operation: 'COUNT',
      displayName: 'story关联的task标题',
      name: 'story_title_name_VS',
      category: 'MEASURE',
      dataType: 'TEXT',
      dataFormat: 'ORIGINAL',
      dataFormatCode: 0,
      params:
        '{"__key__":1697788375996,"originDataType":"TEXT","summaryMethod":"6","displayName":"story关联的task标题","dataFormat":"ORIGINAL","dataType":"TEXT","dataFormatCode":0,"description":"story关联的task标题","updateTime":"2023-09-27 18:17:36","showPop":false,"dataEnable":1,"hideStatus":0,"createTime":"2023-09-27 18:17:36","name":"task_title_name","name":"task_title_name","fieldExpression":"task_title_name","databaseDataType":"String","datasetId":9948,"sortBy":5,"id":654705,"customFormatConfig":"{}","category":"PROPERTY","operation":"SUM"}',
      datasetFieldId: 654705,
      modifyName: false,
      hide: false,
      uniqueKey: '654705_COUNT',
    },
  ],
}
